Background:     #6B7340
Highlight:      #ADB077
Lowlight:       #2D3018
Text:           #0A0E04
Data:           #C8D080
Black:          #0A0E04
EditText:       #989878
EditBG:         #0A0E04
EditBGlow:      #14180A
EditBGhigh:     #1F2410
Brighttext:     #D0D8A0
SelectedBGLow:  #3A4018
SelectedBGHigh: #555E22
LCDHigh:        #D8E060
LCDMid:         #889028
LCDLow:         #404818
CursorRowHigh:  #2A2E18
CursorRowLow:   #1A1E10
