Background:     #B89540
Highlight:      #FFE070
Lowlight:       #604018
Text:           #1A0F00
Data:           #FFD060
Black:          #100800
EditText:       #C0A050
EditBG:         #100800
EditBGlow:      #1C1408
EditBGhigh:     #2A1F10
Brighttext:     #FFE8A0
SelectedBGLow:  #604000
SelectedBGHigh: #806020
LCDHigh:        #FFC000
LCDMid:         #A07000
LCDLow:         #503800
CursorRowHigh:  #3A2C10
CursorRowLow:   #251C08
