Background:     #6E8FB5
Highlight:      #B8D4F0
Lowlight:       #2E4A6C
Text:           #000000
Data:           #B0E0FF
Black:          #050810
EditText:       #C0D8F0
EditBG:         #050810
EditBGlow:      #0C1424
EditBGhigh:     #18243C
Brighttext:     #E0F0FF
SelectedBGLow:  #002060
SelectedBGHigh: #0030A0
LCDHigh:        #80E0FF
LCDMid:         #4080C0
LCDLow:         #204060
CursorRowHigh:  #2A3A55
CursorRowLow:   #1A2A40
