Background:     #1A2E5A
Highlight:      #5078C8
Lowlight:       #060A1A
Text:           #C8D8F0
Data:           #80C0FF
Black:          #02040A
EditText:       #6080B0
EditBG:         #02040A
EditBGlow:      #060A14
EditBGhigh:     #0C1424
Brighttext:     #B0D0FF
SelectedBGLow:  #0A2050
SelectedBGHigh: #1438A0
LCDHigh:        #4080FF
LCDMid:         #2040A0
LCDLow:         #102060
CursorRowHigh:  #14203C
CursorRowLow:   #08101F
