Background:     #2C5038
Highlight:      #6CA078
Lowlight:       #0A180E
Text:           #D8E8D8
Data:           #80E090
Black:          #040804
EditText:       #6C9078
EditBG:         #040804
EditBGlow:      #0A140C
EditBGhigh:     #142018
Brighttext:     #B8E0C0
SelectedBGLow:  #143820
SelectedBGHigh: #245838
LCDHigh:        #40FF80
LCDMid:         #28A050
LCDLow:         #145028
CursorRowHigh:  #1F3A28
CursorRowLow:   #122418
