Background:     #888888
Highlight:      #C8C8C8
Lowlight:       #404040
Text:           #000000
Data:           #FFFFFF
Black:          #000000
EditText:       #B0B0B0
EditBG:         #000040
EditBGlow:      #00004A
EditBGhigh:     #000058
Brighttext:     #FFFFFF
SelectedBGLow:  #0000A0
SelectedBGHigh: #0000D0
LCDHigh:        #FFFFFF
LCDMid:         #A0A0FF
LCDLow:         #4040A0
CursorRowHigh:  #303060
CursorRowLow:   #202050
