Background:     #802818
Highlight:      #E06030
Lowlight:       #2C0A04
Text:           #1A0A04
Data:           #FFB060
Black:          #0A0402
EditText:       #B05030
EditBG:         #0A0402
EditBGlow:      #14080A
EditBGhigh:     #240F0A
Brighttext:     #FFD0A0
SelectedBGLow:  #602000
SelectedBGHigh: #A03808
LCDHigh:        #FF4000
LCDMid:         #C02000
LCDLow:         #601000
CursorRowHigh:  #3A1408
CursorRowLow:   #240C04
